name: 'Submodule Checkout Merge'
author: 'Lori Systems'
description: 'GitHub action for checking out submodules defined within a repository'
inputs:
  ssh-key:
    description: 'SSH private key for private submodule access'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: ['${{ inputs.ssh-key }}']
branding:
  icon: 'box'
  color: 'blue'
